config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :genres do
    resources :scripts
  end
  resources :scripts
  resources :comments, only: [:create, :edit, :update]
  get '/scripts/:id/comments/new', to: 'comments#new'
 root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :script
  belongs_to :user
#  after_create :assign_user
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :scripts
  has_many :users, :through => :scripts

  validates :name, presence: :true
end

app/models/script.rb
class Script < ActiveRecord::Base

  belongs_to :user
  belongs_to :genre
  has_many :comments

  after_save :assign_other_attributes

  validates :title, :logline, presence: :true

  def comments_attributes=(attributes)
    attributes.each do |k,v|
    comments << Comment.find_or_create_by(description: v['description'])

  end
  end

  def genre_attributes=(attributes)
   # Genre.find_or_create_by(name: name)
  end

  def self.alpha_sorted
    Script.all.sort_by {|script| script.title}
  end

  private

  def assign_other_attributes
    self.comments do |comment|
      comment.script = self
      if comment.user_id == nil
        comment.user_id = self.user_id
      end
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :scripts
  has_many :genres, :through => :scripts
  has_many :comments, :through => :scripts

  #@user = User.from_omniauth(request.env["omniauth.auth"])

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      #user.name = auth.info.name   # assuming the user model has a name
     # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
   @comment = Comment.new
  end

  def create
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @genres = Genre.all
  end

  def new
    @genre = current_user.genres.build
  end

  def create
    @genre = current_user.genres.build(genre_params)
    if @genre.save
      flash[:success] = "Your event was successfully created!"
      redirect_to genre_path(@genre)
    else
      render :new
    end
  end

  def show
    @genre = Genre.find(params[:id])
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @genre }
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @scripts = Script.where(genre_id: params[:genre_id])
      respond_to do |f|
      f.html { render :index }
      f.json { render json: @scripts }
     end
  end

  def new
    @script = current_user.scripts.build
    1.times { @script.comments.build }
    if params["genre_id"].present?
      @genre_list = Genre.find([params["genre_id"]])
    else
      @genre_list = Genre.all
    end

  end

  def show
    @script = Script.includes(:genre).find(params[:id])
    respond_to do |f|
      f.html { render :show }
      f.json { render json: @script }
    end
  end

  def create
    @script = current_user.scripts.build(script_params)
    @script.comments do |comment|
      comment.user = current_user
      current_user.comments << comment
      comment.save

      #does this comment have the user_id now?
    end

    #to look at script, script.comments and see if all IDs are there
    if @script.save
      flash[:success] = "Your event was successfully created!"
      redirect_to genre_scripts_path(@script.genre)
    else
      render :new
      1.times { @script.comments.build }
    end
  end

  def update
    @script = Script.find(params[:id])
    if @script.update(script_params)
      @script.save
      redirect_to genre_scripts_path(@script)
    else
      render :new
    end
  end

  def destroy
    @script = Script.find(params[:id])
    @script.destroy
    flash[:notice] = "Script deleted"
    redirect_to genre_scripts_path(@script.genre)
  end

  private

  def script_params
    params.require(:script).permit(:user_id, :title, :logline, :genre_id, comments_attributes: [:description, :user_id])
  end

  def genre_params
    params.require(:genre).permit(:genre_id)
  end

  def comment_params
   params.require(:script).permit(comments_attributes: [:description, :user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = Usersfb.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user#, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/genres/index.html.erb
<h1>Genres</h1>
<p>Select a Genre</p>


<div class="col-md-3">
  <% @genres.each do |genre| %>
  <li><%= link_to genre.name, genre_scripts_path(genre) %></li>
  <% end %>
</div>

app/views/genres/new.html.erb
<%= form_for @genre do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %><br><br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/genres/show.html.erb
<h4><%= @genre.name %></h4>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand">Filmr</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Scripts by Genre", genres_path %></li>
        <li><%= link_to "New Script", new_script_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <p class="nav navbar-text">Logged in as <%= current_user.email %></p>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      </ul>
      <% else %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign In with Facebook", user_omniauth_authorize_path(:facebook) %></li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Filmr</title>
  <link href='https://fonts.googleapis.com/css?family=Cousine:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.13.1/lodash.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>

  <div class="content container">
    <%= yield %>
  </div>

</body>
</html>

app/views/scripts/_form.html.erb
<% if @script.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@script.errors.count, "error") %>
      prohibited this script from being saved:
    </h2>

    <ul>
    <% @script.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @script do |f| %>
<%= f.hidden_field_tag :user_id, current_user.id %>
  <%= f.label "Title" %>
  <%= f.text_field :title %><br><br>
  <%= f.label "Logline" %>
  <%= f.text_field :logline %><br><br>
  <div class="field"><%= f.label :genre_id %><br>

  <%= f.collection_select :genre_id, @genre_list, :id, :name %></div><br>


  <%= f.fields_for :comments do |comment_field| %>
    <%= comment_field.label "Comments" %>
    <div class="help-block">Write a review</div>
    <%= comment_field.text_field :description,  :cols => "20", :rows => "10", placeholder: "Write a review ", hide_label: true %>
  <% end %>
  <br><br>
  <div class="actions"><%= f.submit class: "btn btn-primary" %></div>

<% end %>

<br><br>


<link href='https://fonts.googleapis.com/css?family=Cousine:400,400italic,700,700italic' rel='stylesheet' type='text/css'>

<!-- <h1>New</h1>

<div class="script-box">
  <h1 class="script-title">New Script</h1>
  <form name="scriptForm" ng-submit="actions.submitForm()" class="script-form">
    <div class="form-group row">
      <label class="col-sm-2 mt15">Title</label>
      <input type="text" name="title" placeholder="Title" class="col-sm-10" ng-model="script.title" required />
    </div>

    <div class="form-group row">
      <label class="col-sm-2 mt15">Author</label>
      <input type="text" name="author" class="col-sm-10" ng-model="script.author" required />
    </div>

    <div class="form-group row">
      <label class="col-sm-2 mt15">Genre</label>
      <input type="text" name="genre" class="col-sm-10" ng-model="script.genre" required />
    </div>

    <div class="form-group row">
      <label class="col-sm-2 mt15">Logline</label>
      <textarea type="text" name="logline" rows="5" cols="50" class="col-sm-10 logline-form" ng-model="script.logline" required ></textarea>
    </div>

    <input type="submit"> -->

app/views/scripts/index.html.erb
<br><br>
<h2 class="page-header">Scripts</h2>
<div class="col-md-6">

  <div class="scripts">
  </div>

  <script type="text/javascript" charset="utf-8">
  _.templateSettings.interpolate = /{{([\s\S]+?)}}/g;

  var scriptListItem = _.template(`<div class="script" id="{{id}}">
            <a href="/genres/{{genre.id}}/scripts/{{id}}.json">{{title}}</a>
            </div>`),
    listItem = function (comment) {
      return '<li>' + comment.description + '</li>';
    },
    scriptShowItem = _.template(`<h1>{{title}}</h1><h2>{{logline}}</h2><h3>{{genre.name}}</h3>
      <ul>{{ _.map(comments, listItem) }}</ul>
      <div><a href="/scripts/{{prev_id}}.json" class="script-nav">Prev</a> | <a href="/scripts/{{next_id}}.json" class="script-nav">Next</a></div>`);

  $('.script a, a.script-nav').on('click', function (event) {
    event.preventDefault();
    // grab the href attribute
    var href = $(event.target).attr('href');
    // ajax call with the href attribute // 16
    $.get(href, function(data) {
      var script = data["script"];
      $('.content').html(scriptShowItem(script));
      // pass response into new show script template // 20

      // insert template into page somewhere // 20 $('...').html(....)
    });
  });

  // create another template to show script values

  $(function () {
    $.get("/scripts.json?genre_id=<%= params[:genre_id] %>", function(data) {
      var scripts = data["scripts"];
      $.each(scripts, function (index, script) {
        $('.scripts').append(scriptListItem(script));
      });
    });
  });
  </script>

</div>

app/views/scripts/new.html.erb
<h1>New Script</h1>
<%= render 'form' %>

app/views/scripts/new_genre_script.html.erb
<br><br>
<% if @script.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@script.errors.count, "error") %>
      prohibited this script from being saved:
    </h2>

    <ul>
    <% @script.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @script do |f| %>
<%= f.hidden_field_tag :user_id, current_user.id %>
  <%= f.label "Title" %>
  <%= f.text_field :title %><br><br>
  <%= f.label "Logline" %>
  <%= f.text_field :logline %><br><br>
  <div class="field"><%= f.label :genre_id %><br>
  <%= f.collection_select :genre_id, Genre.find([1]), :id, :name %></div><br>
  <%= f.fields_for :comments do |comment_field| %>
    <%= comment_field.label "Comments" %>
    <div class="help-block">Write a review</div>
    <%= comment_field.text_field :description,  :cols => "20", :rows => "10", placeholder: "Write a review ", hide_label: true %>
  <% end %>
  <br><br>
  <div class="actions"><%= f.submit class: "btn btn-primary" %></div>

<% end %>

app/views/scripts/show.html.erb
<br><h1><%= @script.title.upcase %></h1>
<h3><%= @script.logline %></h3>
<h4><br><%= @script.genre.name %></h4>

<h4 style="text-decoration: underline"><br>comments</h4>
<br><% @script.comments.each do |comment|%>
<li><%= comment.description %><br>
<%= comment.user_id %><br>
<% end %>


<br><br>

<%= form_for @script do |f| %>

<%= f.fields_for :comments, @script.comments.build do |comments_fields| %>
  <%= comments_fields.label "Add your comment" %>
  <div class="help-block">What do you think about this movie?</div>
  <%= comments_fields.text_field :description, :size=>"50", hide_label: true %>
  <% end %>
  <br><br>

  <div class="actions"><%= f.submit class: "btn btn-primary" %></div>
<% end %>



<% if user_signed_in? %>
  <br><br>
  <%= link_to "Erase", genre_script_path, method: :delete, data: { confirm: 'Are you sure?'} %>
<% end %>


<a href="#" class="js-pre" data-id="<%=@script.id%>">Previous script</a> |
<a href="#" class="js-next" data-id="<%=@script.id%>">Next script</a>
<h2 class="scriptTitle"><%= @script.title %></h2>
<h4 class="scriptGenre">Genre: <%= link_to @script.genre.name, genre_path(@script.genre) %></h4>

<div class="commentAction">
  <% if !!@comment_by_current_user %>
    <%= button_to "Edit your comment", edit_comment_path(@comment_by_current_user), method: :get %>
  <% elsif %>
    <%= button_to "comment this script", "/scripts/#{@script.id}/comments/new", method: :get %>
  <% end %>
</div>

<div class="comments">

</div>


<script type="text/javascript" charset="utf-8">
  updateView(parseInt($(".js-next").attr("data-id")));
  var scriptCount;
  $.get("/scripts.json", function(data) { scriptCount = data["scripts"].length; });
  $(".js-next").on("click", function() {
    var nextId = parseInt($(".js-next").attr("data-id")) + 1;
    updateView(nextId);
  });
  $(".js-pre").on("click", function() {
    var curId = parseInt($(".js-next").attr("data-id"));
    if (curId > 1) {
      var nextId = curId - 1;
      updateView(nextId);
    }
  });
  function updateView(nextId) {
    $.get("/scripts/" + nextId + ".json", function(data) {
      var script = data["script"];
      $(".scriptTitle").text(script["title"]);
      $(".scriptGenre a").attr("href", "/genres/" + script["genre"]["id"]).text(script["genre"]["name"]);
      // re-set the id to current on the link
      $(".js-next").attr("data-id", script["id"]);
      // show comments
      $(".comments").empty();
      if (script["comments"].length === 0) {
        $(".comments").html("No reviews...yet!");
      } else {
        $.each(script["comments"], function(index, comment) {
          $(".comments").append('<div class="comment">' +
            '<a href="/users/' + comment["user"]["id"] + '">' + comment["user"]["username"] + '</a>' +
            ' says, "' + comment["content"] + '"' +
            '</div>'
          );
        });
      }
    });
  }
</script>

app/views/welcome/index.html.erb
<br><br><br><br><br><br>
<div style="margin: 0 auto; width:800px; height:300px; padding:50px; padding-top: 50px; border: 1px solid white; text-align:center; font-size:5em">
<h1 style="font-size:1.9em; text-align: center; border">FILMR</h1>
<p style="font-size:.3em">Crowd-rated scripts, shorts, trailers.</p>